-- Run in Supabase SQL Editor to clean up the 'stocks' table (Screener list)

-- 1. Remove orphaned paper trading positions/transactions (if any)
DELETE FROM paper_positions WHERE ticker NOT IN ('AAPL', 'AAVE-USD', 'ABBV', 'ABT', 'ACN', 'ADA-USD', 'ADBE', 'AIG', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'APT-USD', 'ARB-USD', 'ATOM-USD', 'AVAX-USD', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'BNB-USD', 'BRK.B', 'BTC-USD', 'C', 'CAT', 'CHTR', 'CI', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS', 'CVX', 'DE', 'DHR', 'DIS', 'DOGE-USD', 'DOT-USD', 'DUK', 'EMR', 'ETH-USD', 'EXC', 'F', 'FDX', 'FIL-USD', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'INTU', 'ISRG', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LINK-USD', 'LLY', 'LMT', 'LOW', 'LTC-USD', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MO', 'MRK', 'MS', 'MSFT', 'NEAR-USD', 'NEE', 'NFLX', 'NKE', 'NOW', 'NVDA', 'OP-USD', 'ORCL', 'PEP', 'PFE', 'PG', 'PGR', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SCHW', 'SLB', 'SO', 'SOL-USD', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'USDT-USD', 'V', 'VZ', 'WFC', 'WMT', 'XOM', 'XRP-USD');
DELETE FROM paper_transactions WHERE ticker NOT IN ('AAPL', 'AAVE-USD', 'ABBV', 'ABT', 'ACN', 'ADA-USD', 'ADBE', 'AIG', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'APT-USD', 'ARB-USD', 'ATOM-USD', 'AVAX-USD', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'BNB-USD', 'BRK.B', 'BTC-USD', 'C', 'CAT', 'CHTR', 'CI', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS', 'CVX', 'DE', 'DHR', 'DIS', 'DOGE-USD', 'DOT-USD', 'DUK', 'EMR', 'ETH-USD', 'EXC', 'F', 'FDX', 'FIL-USD', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'INTU', 'ISRG', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LINK-USD', 'LLY', 'LMT', 'LOW', 'LTC-USD', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MO', 'MRK', 'MS', 'MSFT', 'NEAR-USD', 'NEE', 'NFLX', 'NKE', 'NOW', 'NVDA', 'OP-USD', 'ORCL', 'PEP', 'PFE', 'PG', 'PGR', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SCHW', 'SLB', 'SO', 'SOL-USD', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'USDT-USD', 'V', 'VZ', 'WFC', 'WMT', 'XOM', 'XRP-USD');

-- 2. Remove orphaned WhatIf scenarios (if any)
DELETE FROM whatif_scenarios WHERE ticker NOT IN ('AAPL', 'AAVE-USD', 'ABBV', 'ABT', 'ACN', 'ADA-USD', 'ADBE', 'AIG', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'APT-USD', 'ARB-USD', 'ATOM-USD', 'AVAX-USD', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'BNB-USD', 'BRK.B', 'BTC-USD', 'C', 'CAT', 'CHTR', 'CI', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS', 'CVX', 'DE', 'DHR', 'DIS', 'DOGE-USD', 'DOT-USD', 'DUK', 'EMR', 'ETH-USD', 'EXC', 'F', 'FDX', 'FIL-USD', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'INTU', 'ISRG', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LINK-USD', 'LLY', 'LMT', 'LOW', 'LTC-USD', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MO', 'MRK', 'MS', 'MSFT', 'NEAR-USD', 'NEE', 'NFLX', 'NKE', 'NOW', 'NVDA', 'OP-USD', 'ORCL', 'PEP', 'PFE', 'PG', 'PGR', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SCHW', 'SLB', 'SO', 'SOL-USD', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'USDT-USD', 'V', 'VZ', 'WFC', 'WMT', 'XOM', 'XRP-USD');

-- 3. Finally, delete them from the main 'stocks' table (the Screener list)
DELETE FROM stocks WHERE ticker NOT IN ('AAPL', 'AAVE-USD', 'ABBV', 'ABT', 'ACN', 'ADA-USD', 'ADBE', 'AIG', 'AMAT', 'AMD', 'AMGN', 'AMZN', 'APT-USD', 'ARB-USD', 'ATOM-USD', 'AVAX-USD', 'AVGO', 'AXP', 'BA', 'BAC', 'BK', 'BKNG', 'BLK', 'BMY', 'BNB-USD', 'BRK.B', 'BTC-USD', 'C', 'CAT', 'CHTR', 'CI', 'CL', 'CMCSA', 'COF', 'COP', 'COST', 'CRM', 'CSCO', 'CVS', 'CVX', 'DE', 'DHR', 'DIS', 'DOGE-USD', 'DOT-USD', 'DUK', 'EMR', 'ETH-USD', 'EXC', 'F', 'FDX', 'FIL-USD', 'GD', 'GE', 'GILD', 'GM', 'GOOG', 'GOOGL', 'GS', 'HD', 'HON', 'IBM', 'INTC', 'INTU', 'ISRG', 'JNJ', 'JPM', 'KHC', 'KO', 'LIN', 'LINK-USD', 'LLY', 'LMT', 'LOW', 'LTC-USD', 'MA', 'MCD', 'MDLZ', 'MDT', 'MET', 'META', 'MO', 'MRK', 'MS', 'MSFT', 'NEAR-USD', 'NEE', 'NFLX', 'NKE', 'NOW', 'NVDA', 'OP-USD', 'ORCL', 'PEP', 'PFE', 'PG', 'PGR', 'PM', 'PYPL', 'QCOM', 'RTX', 'SBUX', 'SCHW', 'SLB', 'SO', 'SOL-USD', 'SPG', 'T', 'TGT', 'TMO', 'TMUS', 'TSLA', 'TXN', 'UNH', 'UNP', 'UPS', 'USB', 'USDT-USD', 'V', 'VZ', 'WFC', 'WMT', 'XOM', 'XRP-USD');
