"""Central ticker lists — imported by all data scripts."""

# yfinance uses different symbols for some tickers.
# Only used by seed scripts (local, 1-time use).
YFINANCE_MAP = {
    "BRK.B": "BRK-B",
    "BF.B": "BF-B",
}


def to_yf(ticker: str) -> str:
    """Convert our DB ticker to yfinance-compatible symbol."""
    return YFINANCE_MAP.get(ticker, ticker)


def from_yf(yf_symbol: str) -> str:
    """Convert yfinance symbol back to our DB ticker."""
    _reverse = {v: k for k, v in YFINANCE_MAP.items()}
    return _reverse.get(yf_symbol, yf_symbol)


def to_twelve_data_crypto(ticker: str) -> str:
    """Convert DB crypto ticker (BTC-USD) to Twelve Data format (BTC/USD)."""
    return ticker.replace("-USD", "/USD")


SP500_TICKERS = [
    "A", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI", "ADM",
    "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG", "AKAM",
    "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP",
    "AMT", "AMZN", "ANET", "AON", "AOS", "APA", "APD", "APH", "APO", "APP",
    "APTV", "ARE", "ARES", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP",
    "AZO", "BA", "BAC", "BALL", "BAX", "BBY", "BDX", "BEN", "BF.B", "BG",
    "BIIB", "BK", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BR", "BRK.B", "BRO",
    "BSX", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CAT", "CB", "CBOE",
    "CBRE", "CCI", "CCL", "CDNS", "CDW", "CEG", "CF", "CFG", "CHD", "CHRW",
    "CHTR", "CI", "CIEN", "CINF", "CL", "CLX", "CMCSA", "CME", "CMG", "CMI",
    "CMS", "CNC", "CNP", "COF", "COIN", "COO", "COP", "COR", "COST", "CPAY",
    "CPB", "CPRT", "CPT", "CRH", "CRL", "CRM", "CRWD", "CSCO", "CSGP", "CSX",
    "CTAS", "CTRA", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "D", "DAL", "DASH",
    "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX", "DHI", "DHR", "DIS",
    "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK", "DVA",
    "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX", "EL",
    "ELV", "EME", "EMR", "EOG", "EPAM", "EQIX", "EQR", "EQT", "ERIE", "ES",
    "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD", "EXPE", "EXR",
    "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FE", "FFIV", "FICO", "FIS",
    "FISV", "FITB", "FIX", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV", "GD",
    "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL", "GLW", "GM",
    "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS",
    "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HOLX", "HON", "HOOD", "HPE",
    "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBKR", "IBM",
    "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU", "INVH", "IP", "IQV",
    "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JBL", "JCI",
    "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS", "KHC", "KIM", "KKR", "KLAC",
    "KMB", "KMI", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX",
    "LII", "LIN", "LLY", "LMT", "LNT", "LOW", "LRCX", "LULU", "LUV", "LVS",
    "LW", "LYB", "LYV", "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK",
    "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MKC", "MLM", "MMM", "MNST",
    "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MS", "MSCI",
    "MSFT", "MSI", "MTB", "MTCH", "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE",
    "NEM", "NFLX", "NI", "NKE", "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS",
    "NUE", "NVDA", "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL", "OKE", "OMC",
    "ON", "ORCL", "ORLY", "OTIS", "OXY", "PANW", "PAYC", "PAYX", "PCAR", "PCG",
    "PEG", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD",
    "PLTR", "PM", "PNC", "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU",
    "PSA", "PSX", "PTC", "PWR", "PYPL", "QCOM", "RCL", "REG",
    "REGN", "RF", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG",
    "RTX", "RVTY", "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA",
    "SNPS", "SO", "SOLV", "SPG", "SPGI", "SRE", "STE", "STLD", "STT",
    "STX", "STZ", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", "TAP",
    "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TGT", "TJX", "TMO",
    "TMUS", "TPL", "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN",
    "TT", "TTD", "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER", "UDR", "UHS",
    "ULTA", "UNH", "UNP", "UPS", "URI", "USB", "V", "VICI", "VLO", "VLTO",
    "VMC", "VRSK", "VRSN", "VRTX", "VST", "VTR", "VTRS", "VZ", "WAB", "WAT",
    "WBD", "WDAY", "WDC", "WEC", "WELL", "WFC", "WM", "WMB", "WMT", "WRB",
    "WSM", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL", "YUM",
    "ZBH", "ZBRA", "ZTS",
]  # ~500 tickers (S&P 500)

# Backward compatibility alias
SP100_TICKERS = SP500_TICKERS

# Top 19 crypto by market cap
CRYPTO_TICKERS = [
    "BTC-USD", "ETH-USD", "USDT-USD", "BNB-USD", "SOL-USD", "XRP-USD",
    "ADA-USD", "DOGE-USD", "AVAX-USD", "DOT-USD",
    "LINK-USD", "ATOM-USD", "LTC-USD", "FIL-USD",
    "NEAR-USD", "APT-USD", "ARB-USD", "OP-USD", "AAVE-USD",
]  # 19 crypto

# Major ETFs — index, sector, bond, commodity, international, thematic
ETF_TICKERS = [
    # Index trackers
    "SPY", "QQQ", "DIA", "IWM",
    # Sector ETFs (11 GICS sectors)
    "XLK", "XLF", "XLE", "XLV", "XLI", "XLP", "XLY", "XLU", "XLRE", "XLC", "XLB",
    # Bond
    "TLT", "BND", "HYG",
    # Commodity
    "GLD", "SLV", "USO",
    # International
    "EFA", "EEM",
    # Thematic
    "ARKK", "SOXX", "XBI",
]  # 25 ETFs

# Combined list for scripts that handle both
ALL_TICKERS = SP500_TICKERS + CRYPTO_TICKERS + ETF_TICKERS

# Official company names for news ticker mapping
COMPANY_NAMES = {
    # S&P 500
    "A": "Agilent", "AAPL": "Apple", "ABBV": "AbbVie", "ABNB": "Airbnb",
    "ABT": "Abbott", "ACGL": "Arch Capital", "ACN": "Accenture", "ADBE": "Adobe",
    "ADI": "Analog Devices", "ADM": "Archer Daniels Midland", "ADP": "ADP",
    "ADSK": "Autodesk", "AEE": "Ameren", "AEP": "American Electric Power",
    "AES": "AES", "AFL": "Aflac", "AIG": "AIG", "AIZ": "Assurant",
    "AJG": "Arthur J. Gallagher", "AKAM": "Akamai", "ALB": "Albemarle",
    "ALGN": "Align Technology", "ALL": "Allstate", "ALLE": "Allegion",
    "AMAT": "Applied Materials", "AMCR": "Amcor", "AMD": "AMD", "AME": "Ametek",
    "AMGN": "Amgen", "AMP": "Ameriprise", "AMT": "American Tower", "AMZN": "Amazon",
    "ANET": "Arista Networks", "AON": "Aon", "AOS": "A. O. Smith", "APA": "APA",
    "APD": "Air Products", "APH": "Amphenol", "APO": "Apollo Global",
    "APP": "AppLovin", "APTV": "Aptiv", "ARE": "Alexandria Real Estate",
    "ARES": "Ares Management", "ATO": "Atmos Energy", "AVB": "AvalonBay",
    "AVGO": "Broadcom", "AVY": "Avery Dennison", "AWK": "American Water Works",
    "AXON": "Axon Enterprise", "AXP": "American Express", "AZO": "AutoZone",
    "BA": "Boeing", "BAC": "Bank of America", "BALL": "Ball", "BAX": "Baxter",
    "BBY": "Best Buy", "BDX": "Becton Dickinson", "BEN": "Franklin Resources",
    "BF.B": "Brown-Forman", "BG": "Bunge Global", "BIIB": "Biogen",
    "BK": "BNY Mellon", "BKNG": "Booking Holdings", "BKR": "Baker Hughes",
    "BLDR": "Builders FirstSource", "BLK": "BlackRock", "BMY": "Bristol Myers Squibb",
    "BR": "Broadridge", "BRK.B": "Berkshire Hathaway", "BRO": "Brown & Brown",
    "BSX": "Boston Scientific", "BX": "Blackstone", "BXP": "BXP",
    "C": "Citigroup", "CAG": "Conagra", "CAH": "Cardinal Health",
    "CARR": "Carrier Global", "CAT": "Caterpillar", "CB": "Chubb",
    "CBOE": "Cboe Global Markets", "CBRE": "CBRE Group", "CCI": "Crown Castle",
    "CCL": "Carnival", "CDNS": "Cadence Design", "CDW": "CDW",
    "CEG": "Constellation Energy", "CF": "CF Industries", "CFG": "Citizens Financial",
    "CHD": "Church & Dwight", "CHRW": "C.H. Robinson", "CHTR": "Charter Communications",
    "CI": "Cigna", "CIEN": "Ciena", "CINF": "Cincinnati Financial",
    "CL": "Colgate-Palmolive", "CLX": "Clorox", "CMCSA": "Comcast",
    "CME": "CME Group", "CMG": "Chipotle", "CMI": "Cummins", "CMS": "CMS Energy",
    "CNC": "Centene", "CNP": "CenterPoint Energy", "COF": "Capital One",
    "COIN": "Coinbase", "COO": "Cooper Companies", "COP": "ConocoPhillips",
    "COR": "Cencora", "COST": "Costco", "CPAY": "Corpay", "CPB": "Campbell's",
    "CPRT": "Copart", "CPT": "Camden Property", "CRH": "CRH",
    "CRL": "Charles River Labs", "CRM": "Salesforce", "CRWD": "CrowdStrike",
    "CSCO": "Cisco", "CSGP": "CoStar Group", "CSX": "CSX", "CTAS": "Cintas",
    "CTRA": "Coterra", "CTSH": "Cognizant", "CTVA": "Corteva", "CVNA": "Carvana",
    "CVS": "CVS Health", "CVX": "Chevron", "D": "Dominion Energy",
    "DAL": "Delta Air Lines", "DASH": "DoorDash", "DD": "DuPont", "DDOG": "Datadog",
    "DE": "Deere", "DECK": "Deckers Brands", "DELL": "Dell Technologies",
    "DG": "Dollar General", "DGX": "Quest Diagnostics", "DHI": "D.R. Horton",
    "DHR": "Danaher", "DIS": "Walt Disney", "DLR": "Digital Realty",
    "DLTR": "Dollar Tree", "DOC": "Healthpeak Properties", "DOV": "Dover",
    "DOW": "Dow", "DPZ": "Domino's", "DRI": "Darden Restaurants",
    "DTE": "DTE Energy", "DUK": "Duke Energy", "DVA": "DaVita",
    "DVN": "Devon Energy", "DXCM": "Dexcom", "EA": "Electronic Arts",
    "EBAY": "eBay", "ECL": "Ecolab", "ED": "Consolidated Edison",
    "EFX": "Equifax", "EG": "Everest Group", "EIX": "Edison International",
    "EL": "Estee Lauder", "ELV": "Elevance Health", "EME": "Emcor",
    "EMR": "Emerson Electric", "EOG": "EOG Resources", "EPAM": "EPAM Systems",
    "EQIX": "Equinix", "EQR": "Equity Residential", "EQT": "EQT",
    "ERIE": "Erie Indemnity", "ES": "Eversource", "ESS": "Essex Property",
    "ETN": "Eaton", "ETR": "Entergy", "EVRG": "Evergy",
    "EW": "Edwards Lifesciences", "EXC": "Exelon", "EXE": "Expand Energy",
    "EXPD": "Expeditors", "EXPE": "Expedia", "EXR": "Extra Space Storage",
    "F": "Ford", "FANG": "Diamondback Energy", "FAST": "Fastenal",
    "FCX": "Freeport-McMoRan", "FDS": "FactSet", "FDX": "FedEx",
    "FE": "FirstEnergy", "FFIV": "F5", "FICO": "Fair Isaac",
    "FIS": "Fidelity National Info", "FISV": "Fiserv", "FITB": "Fifth Third Bancorp",
    "FIX": "Comfort Systems USA", "FOX": "Fox B", "FOXA": "Fox A",
    "FRT": "Federal Realty", "FSLR": "First Solar", "FTNT": "Fortinet",
    "FTV": "Fortive", "GD": "General Dynamics", "GDDY": "GoDaddy",
    "GE": "GE Aerospace", "GEHC": "GE HealthCare", "GEN": "Gen Digital",
    "GEV": "GE Vernova", "GILD": "Gilead Sciences", "GIS": "General Mills",
    "GL": "Globe Life", "GLW": "Corning", "GM": "General Motors",
    "GNRC": "Generac", "GOOG": "Alphabet C", "GOOGL": "Alphabet A",
    "GPC": "Genuine Parts", "GPN": "Global Payments", "GRMN": "Garmin",
    "GS": "Goldman Sachs", "GWW": "W.W. Grainger", "HAL": "Halliburton",
    "HAS": "Hasbro", "HBAN": "Huntington Bancshares", "HCA": "HCA Healthcare",
    "HD": "Home Depot", "HIG": "Hartford Financial", "HII": "Huntington Ingalls",
    "HLT": "Hilton", "HOLX": "Hologic", "HON": "Honeywell", "HOOD": "Robinhood",
    "HPE": "Hewlett Packard Enterprise", "HPQ": "HP", "HRL": "Hormel Foods",
    "HSIC": "Henry Schein", "HST": "Host Hotels", "HSY": "Hershey",
    "HUBB": "Hubbell", "HUM": "Humana", "HWM": "Howmet Aerospace",
    "IBKR": "Interactive Brokers", "IBM": "IBM", "ICE": "ICE", "IDXX": "Idexx Labs",
    "IEX": "IDEX", "IFF": "IFF", "INCY": "Incyte", "INTC": "Intel",
    "INTU": "Intuit", "INVH": "Invitation Homes", "IP": "International Paper",
    "IQV": "IQVIA", "IR": "Ingersoll Rand", "IRM": "Iron Mountain",
    "ISRG": "Intuitive Surgical", "IT": "Gartner", "ITW": "Illinois Tool Works",
    "IVZ": "Invesco", "J": "Jacobs Solutions", "JBHT": "J.B. Hunt", "JBL": "Jabil",
    "JCI": "Johnson Controls", "JKHY": "Jack Henry", "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase", "KDP": "Keurig Dr Pepper", "KEY": "KeyCorp",
    "KEYS": "Keysight", "KHC": "Kraft Heinz", "KIM": "Kimco Realty", "KKR": "KKR",
    "KLAC": "KLA", "KMB": "Kimberly-Clark", "KMI": "Kinder Morgan",
    "KO": "Coca-Cola", "KR": "Kroger", "KVUE": "Kenvue", "L": "Loews",
    "LDOS": "Leidos", "LEN": "Lennar", "LH": "Labcorp", "LHX": "L3Harris",
    "LII": "Lennox International", "LIN": "Linde", "LLY": "Eli Lilly",
    "LMT": "Lockheed Martin", "LNT": "Alliant Energy", "LOW": "Lowe's",
    "LRCX": "Lam Research", "LULU": "Lululemon", "LUV": "Southwest Airlines",
    "LVS": "Las Vegas Sands", "LW": "Lamb Weston", "LYB": "LyondellBasell",
    "LYV": "Live Nation", "MA": "Mastercard", "MAA": "Mid-America Apartment",
    "MAR": "Marriott", "MAS": "Masco", "MCD": "McDonald's",
    "MCHP": "Microchip Technology", "MCK": "McKesson", "MCO": "Moody's",
    "MDLZ": "Mondelez", "MDT": "Medtronic", "MET": "MetLife",
    "META": "Meta Platforms", "MGM": "MGM Resorts", "MKC": "McCormick",
    "MLM": "Martin Marietta", "MMM": "3M", "MNST": "Monster Beverage",
    "MO": "Altria", "MOH": "Molina Healthcare", "MOS": "Mosaic",
    "MPC": "Marathon Petroleum", "MPWR": "Monolithic Power", "MRK": "Merck",
    "MRNA": "Moderna", "MS": "Morgan Stanley",
    "MSCI": "MSCI", "MSFT": "Microsoft", "MSI": "Motorola Solutions",
    "MTB": "M&T Bank", "MTCH": "Match Group", "MTD": "Mettler Toledo",
    "MU": "Micron", "NCLH": "Norwegian Cruise Line", "NDAQ": "Nasdaq",
    "NDSN": "Nordson", "NEE": "NextEra Energy", "NEM": "Newmont",
    "NFLX": "Netflix", "NI": "NiSource", "NKE": "Nike",
    "NOC": "Northrop Grumman", "NOW": "ServiceNow", "NRG": "NRG Energy",
    "NSC": "Norfolk Southern", "NTAP": "NetApp", "NTRS": "Northern Trust",
    "NUE": "Nucor", "NVDA": "Nvidia", "NVR": "NVR", "NWS": "News Corp B",
    "NWSA": "News Corp A", "NXPI": "NXP Semiconductors", "O": "Realty Income",
    "ODFL": "Old Dominion", "OKE": "Oneok", "OMC": "Omnicom",
    "ON": "ON Semiconductor", "ORCL": "Oracle", "ORLY": "O'Reilly Auto",
    "OTIS": "Otis Worldwide", "OXY": "Occidental Petroleum",
    "PANW": "Palo Alto Networks", "PAYC": "Paycom", "PAYX": "Paychex",
    "PCAR": "Paccar", "PCG": "PG&E", "PEG": "PSEG", "PEP": "PepsiCo",
    "PFE": "Pfizer", "PFG": "Principal Financial", "PG": "Procter & Gamble",
    "PGR": "Progressive", "PH": "Parker Hannifin", "PHM": "PulteGroup",
    "PKG": "Packaging Corp", "PLD": "Prologis", "PLTR": "Palantir",
    "PM": "Philip Morris", "PNC": "PNC Financial", "PNR": "Pentair",
    "PNW": "Pinnacle West", "PODD": "Insulet", "POOL": "Pool Corp",
    "PPG": "PPG Industries", "PPL": "PPL", "PRU": "Prudential",
    "PSA": "Public Storage", "PSX": "Phillips 66",
    "PTC": "PTC", "PWR": "Quanta Services", "PYPL": "PayPal",
    "QCOM": "Qualcomm", "RCL": "Royal Caribbean", "REG": "Regency Centers",
    "REGN": "Regeneron", "RF": "Regions Financial", "RJF": "Raymond James",
    "RL": "Ralph Lauren", "RMD": "ResMed", "ROK": "Rockwell Automation",
    "ROL": "Rollins", "ROP": "Roper Technologies", "ROST": "Ross Stores",
    "RSG": "Republic Services", "RTX": "RTX", "RVTY": "Revvity",
    "SBAC": "SBA Communications", "SBUX": "Starbucks", "SCHW": "Charles Schwab",
    "SHW": "Sherwin-Williams", "SJM": "J.M. Smucker", "SLB": "Schlumberger",
    "SMCI": "Super Micro", "SNA": "Snap-on", "SNPS": "Synopsys",
    "SO": "Southern Company", "SOLV": "Solventum", "SPG": "Simon Property",
    "SPGI": "S&P Global", "SRE": "Sempra", "STE": "Steris",
    "STLD": "Steel Dynamics", "STT": "State Street", "STX": "Seagate",
    "STZ": "Constellation Brands",
    "SWK": "Stanley Black & Decker", "SWKS": "Skyworks", "SYF": "Synchrony",
    "SYK": "Stryker", "SYY": "Sysco", "T": "AT&T", "TAP": "Molson Coors",
    "TDG": "TransDigm", "TDY": "Teledyne", "TECH": "Bio-Techne",
    "TEL": "TE Connectivity", "TER": "Teradyne", "TFC": "Truist Financial",
    "TGT": "Target", "TJX": "TJX Companies",
    "TMO": "Thermo Fisher", "TMUS": "T-Mobile", "TPL": "Texas Pacific Land",
    "TPR": "Tapestry", "TRGP": "Targa Resources", "TRMB": "Trimble",
    "TROW": "T. Rowe Price", "TRV": "Travelers", "TSCO": "Tractor Supply",
    "TSLA": "Tesla", "TSN": "Tyson Foods", "TT": "Trane Technologies",
    "TTD": "Trade Desk", "TTWO": "Take-Two Interactive", "TXN": "Texas Instruments",
    "TXT": "Textron", "TYL": "Tyler Technologies", "UAL": "United Airlines",
    "UBER": "Uber", "UDR": "UDR", "UHS": "Universal Health Services",
    "ULTA": "Ulta Beauty", "UNH": "UnitedHealth", "UNP": "Union Pacific",
    "UPS": "UPS", "URI": "United Rentals", "USB": "U.S. Bancorp", "V": "Visa",
    "VICI": "Vici Properties", "VLO": "Valero Energy", "VLTO": "Veralto",
    "VMC": "Vulcan Materials", "VRSK": "Verisk", "VRSN": "VeriSign",
    "VRTX": "Vertex Pharma", "VST": "Vistra", "VTR": "Ventas", "VTRS": "Viatris",
    "VZ": "Verizon", "WAB": "Wabtec", "WAT": "Waters",
    "WBD": "Warner Bros. Discovery", "WDAY": "Workday", "WDC": "Western Digital",
    "WEC": "WEC Energy", "WELL": "Welltower", "WFC": "Wells Fargo",
    "WM": "Waste Management", "WMB": "Williams Companies", "WMT": "Walmart",
    "WRB": "W.R. Berkley", "WSM": "Williams-Sonoma", "WST": "West Pharma",
    "WTW": "Willis Towers Watson", "WY": "Weyerhaeuser", "WYNN": "Wynn Resorts",
    "XEL": "Xcel Energy", "XOM": "ExxonMobil", "XYL": "Xylem",
    "YUM": "Yum! Brands", "ZBH": "Zimmer Biomet", "ZBRA": "Zebra Technologies",
    "ZTS": "Zoetis",
    # Crypto
    "BTC-USD": "Bitcoin", "ETH-USD": "Ethereum", "USDT-USD": "Tether",
    "BNB-USD": "BNB",
    "SOL-USD": "Solana", "XRP-USD": "XRP", "ADA-USD": "Cardano",
    "DOGE-USD": "Dogecoin", "AVAX-USD": "Avalanche", "DOT-USD": "Polkadot",
    "LINK-USD": "Chainlink",
    "ATOM-USD": "Cosmos", "LTC-USD": "Litecoin", "FIL-USD": "Filecoin",
    "NEAR-USD": "NEAR Protocol", "APT-USD": "Aptos", "ARB-USD": "Arbitrum",
    "OP-USD": "Optimism", "AAVE-USD": "Aave",
    # ETFs
    "SPY": "SPDR S&P 500", "QQQ": "Invesco QQQ", "DIA": "SPDR Dow Jones",
    "IWM": "iShares Russell 2000",
    "XLK": "Technology Select", "XLF": "Financial Select", "XLE": "Energy Select",
    "XLV": "Health Care Select", "XLI": "Industrial Select", "XLP": "Consumer Staples Select",
    "XLY": "Consumer Discretionary Select", "XLU": "Utilities Select",
    "XLRE": "Real Estate Select", "XLC": "Communication Services Select",
    "XLB": "Materials Select",
    "TLT": "iShares 20+ Year Treasury", "BND": "Vanguard Total Bond",
    "HYG": "iShares High Yield Corporate",
    "GLD": "SPDR Gold Shares", "SLV": "iShares Silver", "USO": "United States Oil",
    "EFA": "iShares MSCI EAFE", "EEM": "iShares MSCI Emerging",
    "ARKK": "ARK Innovation", "SOXX": "iShares Semiconductor", "XBI": "SPDR Biotech",
}
